"""
Shared configuration, layout discovery, and helpers for the qpyd / qpynb CLIs.

These helpers locate the Quarto project (the directory containing ``_quarto.yml``),
read the relevant settings out of it, and resolve which notebooks a command
should operate on.
"""

import os
import shutil
from pathlib import Path

import yaml

# --- Display / behaviour constants ---------------------------------------

TIMEOUT = 600  # Maximum time (s) allowed for a single notebook execution
YAY = "✓"  # Success marker used in summaries
BOO = "😢"  # Failure marker used in summaries

# --- Layout constants ----------------------------------------------------

CONFIG_NAME = "_quarto.yml"
VARIABLES_PY = "_variables.py"
FREEZE_DIR = "_freeze"
JUPYTER_CACHE_DIR = ".jupyter_cache"

# Notebook file types qpynb knows how to run / convert
NB_SUFFIXES = (".qmd", ".ipynb")

# Directories that never contain runnable source notebooks. Anything whose
# path passes through one of these (or any hidden, dot-prefixed directory) is
# skipped during automatic discovery.
EXCLUDE_DIRS = {
    "_site",
    "_freeze",
    "_extensions",
    "_inv",
    "api",  # generated by `quartodoc build`
    "assets",
    "images",
    "__pycache__",
}


def find_quarto_config(start=None):
    """
    Walk up from ``start`` (default: cwd) looking for ``_quarto.yml``.

    Returns the :class:`~pathlib.Path` to the config file, or ``None`` if no
    config is found in ``start`` or any of its parents.
    """
    start = Path(start or os.getcwd()).resolve()
    for directory in [start, *start.parents]:
        candidate = directory / CONFIG_NAME
        if candidate.exists():
            return candidate
    return None


def load_quarto_config(start=None):
    """
    Load and parse ``_quarto.yml``.

    Returns a ``(data, path)`` tuple, where ``data`` is the parsed dict (empty
    if no config was found) and ``path`` is the config :class:`~pathlib.Path`
    (or ``None``).
    """
    cfg_path = find_quarto_config(start)
    if cfg_path is None:
        return {}, None
    with open(cfg_path) as f:
        data = yaml.safe_load(f) or {}
    return data, cfg_path


def docs_dir(start=None):
    """
    Return the Quarto project directory (where ``_quarto.yml`` lives).

    Falls back to ``start`` (or the cwd) if no config can be found, so callers
    always get a usable directory. **Destructive** operations must use
    :func:`project_root` instead, which never falls back to the cwd.
    """
    cfg_path = find_quarto_config(start)
    if cfg_path is not None:
        return cfg_path.parent
    return Path(start or os.getcwd()).resolve()


def project_root(start=None):
    """
    Return the Quarto project directory only if a ``_quarto.yml`` exists.

    Unlike :func:`docs_dir`, this returns ``None`` when no config is found,
    so destructive operations can refuse to run outside a real project rather
    than acting on an arbitrary cwd.
    """
    cfg_path = find_quarto_config(start)
    return cfg_path.parent if cfg_path is not None else None


def require_tool(name, hint=None):
    """
    Ensure an external command-line tool is available on ``PATH``.

    Raises a clear :class:`RuntimeError` (rather than letting a later
    ``subprocess`` call surface a bare ``FileNotFoundError``) if it is missing.
    """
    if shutil.which(name) is None:
        msg = f"Required tool {name!r} was not found on your PATH."
        if hint:
            msg += f" {hint}"
        raise RuntimeError(msg)
    return name


def get_package_name(start=None, default=None):
    """
    Return the documented package name from the ``quartodoc.package`` config
    key, or ``default`` if it is not set.
    """
    data, _ = load_quarto_config(start)
    quartodoc_cfg = data.get("quartodoc") or {}
    return quartodoc_cfg.get("package", default)


def is_python_qmd(path):
    """Return True if a ``.qmd`` file contains an executable ``{python}`` cell."""
    try:
        text = Path(path).read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return False
    return "```{python}" in text


def _excluded(path, base):
    """
    True if any *directory* component of ``path`` *below* ``base`` is an
    excluded build dir or hidden.

    Exclusion is judged relative to ``base`` (the directory actually being
    scanned), so an out-of-project scan target whose absolute path happens to
    pass through a hidden/excluded directory (e.g. ``~/.cache/proj``) is not
    spuriously skipped.
    """
    try:
        parts = Path(path).resolve().relative_to(Path(base).resolve()).parts
    except ValueError:
        # Not under base; judge only on the filename's own dir components is
        # impossible, so do not exclude (an explicitly targeted path wins).
        return False
    # parts[:-1] are the directory components (drop the filename itself)
    return any(part in EXCLUDE_DIRS or part.startswith(".") for part in parts[:-1])


def discover_notebooks(paths=None, root=None):
    """
    Resolve the list of notebooks a command should operate on.

    Args:
        paths: optional iterable of file or directory paths. Files are taken
            as-is (even plain ``.qmd`` without code cells); directories are
            searched recursively. If omitted, the whole project is scanned.
        root: project root for scanning and exclusion (default: the docs dir).

    Returns a sorted, de-duplicated list of resolved :class:`~pathlib.Path`
    objects. During scanning, build/output directories and hidden directories
    are skipped, and ``.qmd`` files without ``{python}`` cells are ignored
    (they are prose pages, not notebooks).
    """
    root = Path(root or docs_dir()).resolve()
    results = []
    seen = set()

    def add(candidate, from_scan, base):
        candidate = Path(candidate).resolve()
        if candidate in seen:
            return
        if not candidate.is_file() or candidate.suffix not in NB_SUFFIXES:
            return
        if from_scan:
            if _excluded(candidate, base):
                return
            if candidate.suffix == ".qmd" and not is_python_qmd(candidate):
                return
        seen.add(candidate)
        results.append(candidate)

    if paths:
        for raw in paths:
            target = Path(raw)
            if target.is_dir():
                # Exclusion is judged relative to the scanned dir, not root.
                for suffix in NB_SUFFIXES:
                    for found in target.rglob(f"*{suffix}"):
                        add(found, from_scan=True, base=target)
            else:
                # Explicitly named file: include it even if it is a prose .qmd
                add(target, from_scan=False, base=root)
    else:
        for suffix in NB_SUFFIXES:
            for found in root.rglob(f"*{suffix}"):
                add(found, from_scan=True, base=root)

    return sorted(results)
